---
abstract: 'Drop-in replacement for sprintf(), with named parameter support'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-sprintfn
requires:
  Exporter::Lite: 0
  Test::More: 0.96
  perl: 5.010000
resources:
  homepage: http://search.cpan.org/dist/Text-sprintfn/
  repository: http://github.com/sharyanto/perl-Text-sprintfn
version: 0.02
